In [21]:
import array

In [22]:
arr=array.array('i',[1,2,3,4,5])
print(arr)

array('i', [1, 2, 3, 4, 5])


In [2]:
import numpy as np

In [9]:
a=np.array([1,2,3,4,5,'a'])

In [10]:
print(a)

['1' '2' '3' '4' '5' 'a']


In [12]:
arr.insert(0,6)

In [13]:
arr

array('i', [6, 1, 2, 3, 4, 5])

In [14]:
arr.insert(4,7)

In [15]:
arr

array('i', [6, 1, 2, 3, 7, 4, 5])

In [16]:
for i in arr:
    print(i)

6
1
2
3
7
4
5


In [17]:
for i in range(0,len(arr)):
    print(arr[i])

6
1
2
3
7
4
5


In [36]:
arr1=np.array([1,2,3,4,5])
arr2=np.delete(arr1,1)
arr1
arr2

array([1, 3, 4, 5])

In [35]:
print(arr1)

[1 2 3 4 5]


In [15]:
array=np.array([1,2,3,4,5])
num=5
for i in array:
    if i==num:
        print(i)

5


In [23]:
arr.remove(3)

In [24]:
arr

array('i', [1, 2, 4, 5])

In [37]:
import numpy as np

In [38]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])

In [39]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
0


In [42]:
np.append(arr,10,4)

AxisError: axis 4 is out of bounds for array of dimension 1

In [45]:
arr=np.insert(arr,1,4)

In [54]:
arr1=np.array([2,3,4,5])
arr1=np.append(arr,arr1)

In [51]:
a=[1,2,3,9]

In [52]:
arr.fromlist(a)

AttributeError: 'numpy.ndarray' object has no attribute 'fromlist'

In [53]:
import array as arr

# creating an integer data type array
x = arr.array('i', [1,2,3,4,5,6,7])


# creatomg a list
y = [8, 9, 10]

# using the fromlist() function
x.fromlist(y)

# Printing the new array
print(x)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [57]:
np.delete(arr1,4)

array([<module 'array' (built-in)>, 2, 3, 4], dtype=object)

In [59]:
for i in arr1:
    print(i)

<module 'array' (built-in)>
2
3
4
5


In [61]:
array=np.array([1,2,3,4,5,5,6])
np.pop(array)

AttributeError: module 'numpy' has no attribute 'pop'

In [62]:
l=[1,2,3,4,5]
l.pop()

5

In [63]:
l

[1, 2, 3, 4]

In [77]:
#initialize arrays
import array
array_one = array.array("i", [1, 2, 3])


#print buffer info
print (array_one)
print (array_one.buffer_info())
array_one.reverse()

array('i', [1, 2, 3])
(2441890502096, 3)


In [68]:
array_one

array('i', [3, 2, 1])

In [69]:
count=array_one.count(1)

In [70]:
count

1

In [74]:
arr1=str(array_one)

In [75]:
arr1

"array('i', [3, 2, 1])"

In [78]:
ar=array_one.tolist()

In [79]:
ar

[3, 2, 1]

In [81]:
char_array=array.array("u","a")

In [84]:
new_array="hello"
char_array.fromstring(new_array)

AttributeError: 'array.array' object has no attribute 'fromstring'

In [85]:
from array import array

# Original character array
char_array = array('u', 'Hello')

# String to append
string_to_append = ' World'

# Append each character of the string to the array
char_array.fromstring(string_to_append)

# Convert back to string to display
resulting_string = char_array.tounicode()

print(resulting_string)


AttributeError: 'array.array' object has no attribute 'fromstring'

In [86]:
char_list = ['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']

In [87]:
char_list[:]

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']

In [88]:
char_list[0:3]

['H', 'e', 'l']

In [90]:
char_list[::-1]

['d', 'l', 'r', 'o', 'W', ' ', 'o', 'l', 'l', 'e', 'H']

In [91]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
arr1=np.full((2, 3), fill_value=90)
arr1

array([[90, 90, 90],
       [90, 90, 90]])

In [98]:
new_array=np.insert(arr,1,[11,22,33],axis=0)

In [99]:
new_array

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [100]:
len(new_array)

4

In [101]:
len(new_array[0])

3

In [103]:
for i in new_array:
    print(i)

[1 2 3]
[11 22 33]
[4 5 6]
[7 8 9]


In [105]:
for i in range(len(new_array)):
    for j in range(len(new_array[0])):
        print(new_array[i][j])

1
2
3
11
22
33
4
5
6
7
8
9
